---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: payments=yousif101/payments
    argocd-image-updater.argoproj.io/payments.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: payments-dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
        - name: image.repository
          value: yousif101/payments
        - name: service.port
          value: '32180'
        - name: livenessProbe.httpGet.path
          value: /healthz
        - name: readinessProbe.httpGet.path
          value: /healthz
        - name: image.tag
          value: 0.1.0
    path: helm-charts/payments
    repoURL: https://github.com/yousif609230/argocd-prod.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
